default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: issue_tracker_development
  host: localhost
  username: postgres
  password: password

test:
  <<: *default
  database: issue_tracker_test
  host: localhost
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
  # Let the DATABASE_URL handle everything