# Use the local file system to store uploaded files
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use Amazon S3 to store uploaded files (uncomment and configure as needed)
# amazon:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
#   secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#   region: <%= Rails.application.credentials.dig(:aws, :region) %>
#   bucket: <%= Rails.application.credentials.dig(:aws, :bucket) %>
